AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: email-verifier-stack

Globals:
  Function:
    Runtime: nodejs18.x
    Timeout: 100
    MemorySize: 128
    Architectures:
      - "x86_64"

Resources:
  EmailVerifier:
    Type: AWS::S3::Bucket
  #   Properties:
  #     BucketName: "'email-verifier-function'"
  EmailTable:
    Type: AWS::DynamoDB::Table
    Properties: 
      TableName: "email-table"
      AttributeDefinitions: 
        - AttributeName: email
          AttributeType: S
      KeySchema: 
        - AttributeName: email
          KeyType: HASH
      ProvisionedThroughput: 
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1

  # Each Lambda function is defined by properties:
  # https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction

  # This is a Lambda function config associated with the source code: email-verifier.mjs
  emailVerifierFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: email-verifier
      Handler: src/email-verifier.handler
      Description: A Lambda function that returns a static string.
      Tracing: Active
      Environment:
        Variables:
          TABLE_NAME: email-table
          IS_CORS: true
          FROM_EMAIL: mark@handex.io
          EMAIL_VERIFIED_URL: "https://handex.io/email-verified"
          FUNCTION_URL: "https://z2z4aaf77ua232x5h5iad6f7gq0lnrwf.lambda-url.us-east-1.on.aws"
      Policies:
        # Give Lambda basic execution Permission to the emailVerifier
        - AWSLambdaBasicExecutionRole
        - AmazonSESFullAccess
      FunctionUrlConfig:
        AuthType: NONE
        Cors:
          AllowMethods:
          - POST
          - GET
          AllowOrigins:
          - https://handex.io
          - http://localhost

  DbConnector:
    Type: AWS::Serverless::Connector
    Properties:
      Source:
        Id: emailVerifierFunction
      Destination:
        Id: EmailTable
      Permissions:
      - Read
      - Write
Outputs:
  lambdaURL:
    Description: Email-sender Lambda URL
    Value: !GetAtt emailVerifierFunctionUrl.FunctionUrl
