AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: email-verifier-stack
Globals:
  Function:
    Runtime: nodejs18.x
    Timeout: 100
    MemorySize: 128
    Architectures:
    - x86_64
Resources:
  EmailVerifier:
    Type: AWS::S3::Bucket
  EmailTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: email-table
      AttributeDefinitions:
      - AttributeName: email
        AttributeType: S
      - AttributeName: verificationKey
        AttributeType: S
      KeySchema:
      - AttributeName: email
        KeyType: HASH
      - AttributeName: verificationKey
        KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
  helloFromLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: email-verifier
      Handler: src/email-verifier.handler
      Description: A Lambda function that returns a static string.
      Environment:
        Variables:
          TABLE_NAME: email-table
          FROM_EMAIL: admin@thefullertonian.com
      Policies:
      - AWSLambdaBasicExecutionRole
      FunctionUrlConfig:
        AuthType: NONE
        Cors:
          AllowMethods:
          - POST
          - GET
          AllowOrigins:
          - https://handex.io
          - http://localhost
      CodeUri: helloFromLambdaFunction
      Layers:
      - Fn::GetAtt:
        - AwsSamAutoDependencyLayerNestedStack
        - Outputs.helloFromLambdaFunction8583c9baDepLayer
    Metadata:
      SamResourceId: helloFromLambdaFunction
  DbConnector:
    Type: AWS::Serverless::Connector
    Properties:
      Source:
        Id: helloFromLambdaFunction
      Destination:
        Id: EmailTable
      Permissions:
      - Read
      - Write
  AwsSamAutoDependencyLayerNestedStack:
    DeletionPolicy: Delete
    Metadata:
      CreatedBy: AWS SAM CLI sync command
    Properties:
      TemplateURL: D:\T3\Projects\self\email-verifier\.aws-sam\auto-dependency-layer\adl_nested_template.yaml
    Type: AWS::CloudFormation::Stack
